insert into Bohaterowie values (6,"Beata","Mag","Uczenie programowania nietechnicznych",1000)
insert into Ekwipunek values (9,6,"Replit",1)
insert into Bohaterowie values (7,"BNPBeata","Magik","Uczenie programowania nietechnicznych",1000)
insert into Ekwipunek values (9,6,"Replittt",1)
insert into Bohaterowie values (7,"Robert","Farmer","Pielęgnacja sadu",1000)
insert into Ekwipunek values (9,6,"Traktor",1)
