insert into Bohaterowie values (7,"BNPBeata","Miro","Uczenie programowania nietechnicznych",1000)
insert into Ekwipunek values (9,6,"Replittt",1)
insert into Bohaterowie values (7,"Robert","Farmer","Pielęgnacja sadu",1000)
insert into Ekwipunek values (9,6,"Traktor",1)
insert into Bohaterowie values (7"Łukasz","Mistrz","Mistrz Młyna",10)
insert into Ekwipunek values (10,7,"Scrum Guide",2)